#DELETE user by valid id
DELETE http://localhost:3000/api/users/db5b6794-c3f1-4011-8bcd-9aa9d5d4d333
Content-Type: application/json


###
#User with invalid id
DELETE http://localhost:3000/api/users/db5b6794-c3f1-4011-8bcd-9aa9d5d4d555
Content-Type: application/json

